In [21]:
import pandas as pd
df = pd.read_csv('marketing_campaign.csv')

In [22]:
df.head()

  ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse
0  5524\t1957\tGraduation\tSingle\t58138\t0\t0\t0...
1  2174\t1954\tGraduation\tSingle\t46344\t1\t1\t0...
2  4141\t1965\tGraduation\tTogether\t71613\t0\t0\...
3  6182\t1984\tGraduation\tTogether\t26646\t1\t0\...
4  5324\t1981\tPhD\tMarried\t58293\t1\t0\t19-01-2...

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                    --------------  -----
 0   ID	Year_Birth	Education	Marital_Status	Income	Kidhome	Teenhome	Dt_Customer	Recency	MntWines	MntFruits	MntMeatProducts	MntFishProducts	MntSweetProducts	MntGoldProds	NumDealsPurchases	NumWebPurchases	NumCatalogPurchases	NumStorePurchases	NumWebVisitsMonth	AcceptedCmp3	AcceptedCmp4	AcceptedCmp5	AcceptedCmp1	AcceptedCmp2	Complain	Z_CostContact	Z_Revenue	Response  2240 non-null   object
dtypes: object(1)
memory usage: 17.6+ KB

In [24]:
df.describe()

       ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse
count                                                2240
unique                                               2240
top     1448\t1963\tMaster\tMarried\t33562\t1\t2\t25-0...
freq                                                    1

In [27]:
df.isnull().sum().sort_values(ascending=False)

ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse    0
dtype: int64

In [29]:
missing_values = df.isnull().sum()

In [30]:
missing_values[missing_values>0]

Series([], dtype: int64)

In [31]:
print("Total duplicate rows:",df.duplicated().sum())

Total duplicate rows: 0

In [36]:
print(df.columns)

Index(['ID\tYear_Birth\tEducation\tMarital_Status\tIncome\tKidhome\tTeenhome\tDt_Customer\tRecency\tMntWines\tMntFruits\tMntMeatProducts\tMntFishProducts\tMntSweetProducts\tMntGoldProds\tNumDealsPurchases\tNumWebPurchases\tNumCatalogPurchases\tNumStorePurchases\tNumWebVisitsMonth\tAcceptedCmp3\tAcceptedCmp4\tAcceptedCmp5\tAcceptedCmp1\tAcceptedCmp2\tComplain\tZ_CostContact\tZ_Revenue\tResponse'], dtype='object')

In [38]:
for col in df.columns:
    print(f" '{col}':{len(col)}")

 'ID	Year_Birth	Education	Marital_Status	Income	Kidhome	Teenhome	Dt_Customer	Recency	MntWines	MntFruits	MntMeatProducts	MntFishProducts	MntSweetProducts	MntGoldProds	NumDealsPurchases	NumWebPurchases	NumCatalogPurchases	NumStorePurchases	NumWebVisitsMonth	AcceptedCmp3	AcceptedCmp4	AcceptedCmp5	AcceptedCmp1	AcceptedCmp2	Complain	Z_CostContact	Z_Revenue	Response':360

In [43]:
df.columns = [col.strip().lower()
for col in df.columns]

In [48]:
df = pd.read_csv('marketing_campaign.csv', sep = '\t')
df.columns = df.columns.str.strip().str.lower()
df['dt_customer']=pd.to_datetime(df['dt_customer'], format = '%d-%m-%Y')
print(df['dt_customer'].isnull().sum())

0

In [49]:
df.describe()

,id,year_birth,income,kidhome,teenhome,dt_customer,recency,mntwines,mntfruits,mntmeatproducts,...,numwebvisitsmonth,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,2013-07-10 10:01:42.857142784,49.109375,303.935714,26.302232,166.950000,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,2012-07-30 00:00:00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,2013-01-16 00:00:00,24.000000,23.750000,1.000000,16.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,2013-07-08 12:00:00,49.000000,173.500000,8.000000,67.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,2013-12-30 06:00:00,74.000000,504.250000,33.000000,232.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,2014-06-29 00:00:00,99.000000,1493.000000,199.000000,1725.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,NaN,28.962453,336.597393,39.773434,225.715373,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   object
 3   marital_status       2240 non-null   object
 4   income               2216 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   datetime64[ns]
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(25), object(2)
memory usage: 507.6+ KB

In [52]:
df['income'] = pd.to_numeric(df['income'], errors='coerce')

In [53]:
df['education'] = df['education'].str.lower().str.strip()
df['marital_status'] = df['marital_status'].str.lower().str.strip()

In [54]:
df['year_birth'] = df['year_birth'].replace(1900, df['year_birth'].median())

In [55]:
from datetime import date
df['age'] = date.today().year - df['year_birth']

In [56]:
from datetime import date
df['age'] = date.today().year - df['year_birth']

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   object
 3   marital_status       2240 non-null   object
 4   income               2216 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   datetime64[ns]
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
 29  age                  2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(26), object(2)
memory usage: 525.1+ KB

In [58]:
df.describe()

,id,year_birth,income,kidhome,teenhome,dt_customer,recency,mntwines,mntfruits,mntmeatproducts,...,acceptedcmp3,acceptedcmp4,acceptedcmp5,acceptedcmp1,acceptedcmp2,complain,z_costcontact,z_revenue,response,age
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000,2240.000000
mean,5592.159821,1968.837054,52247.251354,0.444196,0.506250,2013-07-10 10:01:42.857142784,49.109375,303.935714,26.302232,166.950000,...,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107,56.162946
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,2012-07-30 00:00:00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,29.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,2013-01-16 00:00:00,24.000000,23.750000,1.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,48.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,2013-07-08 12:00:00,49.000000,173.500000,8.000000,67.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,55.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,2013-12-30 06:00:00,74.000000,504.250000,33.000000,232.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000,66.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,2014-06-29 00:00:00,99.000000,1493.000000,199.000000,1725.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000,132.000000
std,3246.662198,11.895509,25173.076661,0.538398,0.544538,NaN,28.962453,336.597393,39.773434,225.715373,...,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274,11.895509

In [59]:
df['education'].unique()

array(['graduation', 'phd', 'master', 'basic', '2n cycle'], dtype=object)

In [60]:
df['total_spent'] = df['mntwines'] + df['mntfruits'] + df['mntmeatproducts'] + df['mntfishproducts'] + df['mntsweetproducts'] + df['mntgoldprods']

In [61]:
df['total_kids'] = df['kidhome'] + df['teenhome']

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   object
 3   marital_status       2240 non-null   object
 4   income               2216 non-null   float64
 5   kidhome              2240 non-null   int64
 6   teenhome             2240 non-null   int64
 7   dt_customer          2240 non-null   datetime64[ns]
 8   recency              2240 non-null   int64
 9   mntwines             2240 non-null   int64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
 29  age                  2240 non-null   int64
 30  total_spent          2240 non-null   int64
 31  total_kids           2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(28), object(2)
memory usage: 560.1+ KB